### ISSUE TITLE
Migrate to trellis-ldp/trellis

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis-cassandra#21]
For 0.8 release, migrate `trellis-cassandra` to the trellis-ldp/trellis Github org.

**Comment by ajs6f** [comment]
As per https://github.com/ajs6f/trellis-cassandra/pull/16#issuecomment-439183001, this could and should include integration with CircleCI.

**Comment by acoburn** [comment]
Do you mean migrate to the trellis-ldp github org or the trellis-ldp/trellis repository? I'd think the former would be simple and straight-forward; the latter would be pretty complicated.

**Comment by ajs6f** [comment]
The org, as I write above. I don't even want to think about party-crashing my [Rowdy Roddy Piper of a Maven setup](https://www.youtube.com/watch?v=EtIXTawoX0k) into your elegant and refined build.

**Comment by acoburn** [comment]
👍 on moving to the org. You should be able to move this repo at any time. I don't know if you can migrate a project to the org, too, but feel free to create a new one at: https://github.com/orgs/trellis-ldp/projects

**Comment by ajs6f** [comment]
Done after https://github.com/trellis-ldp/trellis-cassandra/commit/a5b9a6e2d4e6f1b4cae40628da79eb7c0c42afd7.
