### ISSUE TITLE
Replace .distinct() stream filtering with CQL

### ISSUE THREAD

**Issue by gregjan** [trellis-ldp/trellis-cassandra#55]
The .distinct() stream method will creating buffering on the front-end nodes that may be significant for containers with many modifications/mementos. Instead we can use CQL, perhaps adding a "LIMIT 1" to the query in question. Since *any* row will suffice to establish the contains relationship and since the containment table is partitioned by container id, it should work.

**Comment by ajs6f** [comment]
@gregjan Can you give an example of the duplicate Memento triples? Also, does the same duplication show up in the HTTP _headers_?

**Comment by gregjan** [comment]
I never observed the duplication in headers. The duplication I saw during testing came about when the same child was posted multiple times to a parent. I could work up an example later today I think.

**Comment by ajs6f** [comment]
Ok, thank you that would help a great deal. I'll want to take the opportunity to make sure the schema is affording us as much performance as it can.

**Comment by gregjan** [comment]
Okay here is the sequence that will create the duplicate timestamps rows in basiccontainment, straight from my history:
```
 1351  curl -v -XPOST -H "Slug: containerA" -H "Link: <http://www.w3.org/ns/ldp#BasicContainer>; rel=\"type\"" http://ciber-vs1.umd.edu:10080
 1352  curl -v -XPOST -H "Slug: containerB" -H "Link: <http://www.w3.org/ns/ldp#BasicContainer>; rel=\"type\"" http://ciber-vs1.umd.edu:10080/containerA
 1353  curl -v -XPUT -H "Link: <http://www.w3.org/ns/ldp#BasicContainer>; rel=\"type\"" http://ciber-vs1.umd.edu:10080/containerA/containerB
 1
```

So I the PUT returns a 204 No Content, but it still creates a row in the table:
```
cqlsh:trellis> select * from basiccontainment where container = 'trellis:data/containerA' ;

 container               | identifier                         | created
-------------------------+------------------------------------+--------------------------------------
 trellis:data/containerA | trellis:data/containerA/containerB | 8fdc0350-5005-11e9-b90b-7fc79f48ce33
 trellis:data/containerA | trellis:data/containerA/containerB | 6d1e6d80-5005-11e9-b90b-7fc79f48ce33
```

You can repeat PUT as many times as you like. If you try the POST again, it returns a 409 Conflict and doesn't create a row. Now then, this is pretty weird how I used the REST verbs here, but that was how a particular test was coded at the time. (I think it was actually just using PUTs and not POST.)

**Comment by ajs6f** [comment]
Thank you, investigating…

**Comment by ajs6f** [comment]
Just so I understand the issue, the problem here is that you created a bunch of Mementos fine (204 is exactly what you would expect from a successful `PUT` in that way) but then when you go to retrieve the triples of `containerA`, you get many repeated`ldp:contains` triples pointing at `containerB`, one for each memento (`PUT` you did). Right?

**Comment by ajs6f** [comment]
@gregjan Can you check this PR:

https://github.com/trellis-ldp/trellis-cassandra/pull/59

and confirm that it fixes the bug? It did for me, but I want _confirmation_. I ended up needing to adjust the schema (INCOMPATIBLE SCHEMA CHANGE ALERT!) _and_ use a `DISTINCT` query. I too hoped to be able to use `LIMIT`, but that wouldn't properly deal with multiple contained resources, as I'm reasoning now.

**Comment by ajs6f** [comment]
Actually, I might be able to get rid of the `DISTINCT`, so hang on a bit...

**Comment by ajs6f** [comment]
Nope, never mind. 🤷‍♂️ Give this PR a shot please.

**Comment by ajs6f** [comment]
@gregjan, I believe my PR will fix your immediate concern (the duplicate triples) but the cost is too high (distinct-ing anywhere, at the Trellis node or the C* node). The root problem is my use of a materialized view (MV) for the containment index. The primary key of the base table must be present  in the primary key of any C* MV, and that means that in no way can an MV support grouping. But that's just what we need (grouping by container). I'm getting a quasi-grouping effect via using an MV to pivot, using `DISTINCT`, and filtering, but it's hacky, frankly, and it forces us to use filtering over a table, which is bad territory for C*.
I didn't want to go to the trouble of making the kinds of guarantees one has to consider with a view or index (especially not over a system that is as intentionally weak as C*), so I tried to use a C*-native alternative, but I just don't see how we can use it now.
I want to consider all that in relation to https://github.com/trellis-ldp/trellis-cassandra/issues/56, as well. 
I'm happy for you to use this PR (if/when you confirm that it works for you) but I think we are going to have to revisit the whole design of containment in `t-c*` before 1.0.

**Comment by gregjan** [comment]
I will be able to test this tomorrow morning. Hopefully before our meeting. Is one solution to simply add another table? That seems to be the common C* practice, i.e. to design the schemas for queries.

**Comment by ajs6f** [comment]
@gregjan I'm surprised that "distinct"ing is faster on the front-end, but I am ready to change the code. Can we possibly do a pair of runs with everything held constant except the place where we do the deduping? I would be happy to provide two branches for the purpose...

**Comment by gregjan** [comment]
In that particular setting, it was apparently so. I agree that a controlled
comparison is best. I had an unrelated config problem when I tried to test
on Tuesday morning, so I have to resolve that issue first, which was
apparently something network related and not Trellis.

**Comment by ajs6f** [comment]
Ok, cool, let me know if I can help!

**Comment by ajs6f** [comment]
I've realized that there's an additional wrinkle to this: earlier Mementos of a container should have the containment triples that the container had at that time, which means that we do in fact need to store containment information that is distinguished by both identifier and creation (as rows in the current `mutabledata` table are now).

**Comment by acoburn** [comment]
I know you're overriding the `MementoService::put` method (i.e. as a no-op) in order to handle all of this logic internally in the T-C* implementation, but if you need a mechanism to fetch all the current data about a resource, [this part of the http layer](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/impl/MutatingLdpHandler.java#L128-L133) will do much of this for you. It may still be more efficient to handle this all internally in the T-C* implementation, but I wanted to just mention this.

**Comment by ajs6f** [comment]
Is that called for every mutating request? So I could get a "snapshot" at that moment and record out the containment triples then?

**Comment by acoburn** [comment]
That's called for every mutating request on the specific resource being mutated (it isn't called on a parent container when a new resource is created or when an existing resource is deleted). This does mean that you'd need to implement `MementoService::put` [here](https://github.com/trellis-ldp/trellis-cassandra/blob/master/impl/src/main/java/edu/si/trellis/CassandraResourceService.java#L195-L198), but at this point you will have a snapshot of the current state of the resource (modulo any eventual consistency from Cassandra itself, so there may be additional considerations there).

**Comment by ajs6f** [comment]
No, that true, but it's _only_ the containers that matter here. We have no problem with the current Memento action for non-container resources. 

But what about `::touch`? Isn't that called on the container exactly when a mutation occurs to a contained resource?

**Comment by acoburn** [comment]
the `::touch` method is there to update the last-modified date of a parent container (or membership resource). The HTTP layer doesn't expect any sort of memento-related interaction to take place with `::touch`.

**Comment by ajs6f** [comment]
No, sorry for the confusion,  I'm saying that `::touch` is necessarily called on a container when a contained resource "receives" a new version, right? And at that moment, the HTTP layer has in hand the following info:

1. The resource
2. The URI of the container
3. Whether the contained has been added to the container (`POST` or `PUT-with-containment`), changed (`PUT`) or, deleted (`DELETE`)

**Comment by acoburn** [comment]
> `::touch` is necessarily called on a container when a contained resource "receives" a new version, right?

Not necessarily. `::touch` is called under the following circumstances:

* A new resource is added to a container (via POST)
* A contained resource is deleted from a container
* A resource is modified that is contained by an indirect container, then `::touch` is called on that target (membership) resource

For all other cases where an existing, contained resource is updated (e.g via PATCH or PUT), the parent container does not receive a `::touch` method call (unless it is an LDP-IC and is, itself, the target of the ldp:membershipResource property).

But yes, the HTTP layer does have all of the information you mention above.

**Comment by ajs6f** [comment]
Hang on, so our "quantum of change" (as in what will bump the mod date) for a container includes [new contained resource], [delete contained resource], but _not_ [replace contained resource]?

**Comment by acoburn** [comment]
Correct. Why would an update on a child resource change the parent's last-mod date? The same `ldp:contains` triple will appear before and after the update. There's nothing about the representation of the parent container that changes when a child resource is updated.

**Comment by ajs6f** [comment]
I'm not sure that I accept that argument, because if you use a `Prefer` header, the container representation needn't change when things are added or deleted.

**Comment by acoburn** [comment]
Yes, and with `Prefer` headers, there will be plenty of cases where a resource's representation doesn't change, yet we're still changing the last-mod (and ETag) values because _some triples changed_ on that resource -- even if those modified triples are omitted from the representation.

That, at least, has been the standard by which we determine whether a resource's last-mod value changes: have _any_ triples changed? If no triples change, then the last-mod value does not change.

**Comment by ajs6f** [comment]
Hm. I'm wondering now if perhaps `::touch` conflates two things: one, that a change in the last-mod value for the container should be made, and two, a change in containment _may_ have occurred and the backend should do whatever is needed to record that. In other words, I wonder if I was perhaps quite wrong to ask for `::touch`. Maybe it would be better to make backends figure out for themselves when to "touch" a container.

**Comment by acoburn** [comment]
And for the LDP-IC case, there may be a change in membership triples (as opposed to containment).

The code previously required that a persistence impl had to figure out for itself when the last-mod date of a container/resource had to be updated. And while that is a possibility, the code involved there is sort of complicated, and there is a huge advantage to having it all in one place and not having to implement the same logic in each persistence layer.

Maybe I don't really understand what you're trying to accomplish here. Is it just that you want the Mementos to include all of the ldp:contains triples at the moment the resource was modified?

**Comment by ajs6f** [comment]
It's the container that is at stake. I want the representation of the container that was current when the addition/deletion of a contained resource began. If I have that, I can record the containment or membership triples right then. If I don't, I have to go compute them, which is perfectly do-able, but is a  C* antipattern-- reading before writing.

**Comment by acoburn** [comment]
To be honest, there is already some hand-waving that happens for containers and memento resources. It is a non-goal to be able to capture the representation of an arbitrary resource at any arbitrary point in time. For example, consider the following sequence:

Time 1: /container is created (a memento for /container is created)
Time 2: /container is modified to include more user-managed triples (a memento for /container is created)
Time 3: /container/child1 is created (a memento for /container/child1 is created, no memento is created for /container)
Time 4: /container is modified to include more user-managed triples (a memento for /container is created, including the `<> ldp:contains <./child1>` triple)

Here, if a memento is requested for /container after time 3 and before time 4, it would not contain the ldp:contains triple. Personally, I'm OK with that, because the Memento will report that it is accurate as of "time 2". That's how it works in the Triplestore and RDBMS implementations -- for those, Trellis just grabs a full snapshot of the resource _after making a change_ and records that as the new memento.

**Comment by ajs6f** [comment]
Hang on, I'm confused. As usual. I thought [we](https://github.com/trellis-ldp/trellis-cassandra/issues/55#issuecomment-483403196) said [above](https://github.com/trellis-ldp/trellis-cassandra/issues/55#issuecomment-483404158) that step 3 specifically _would_ create a Memento for the container?!

**Comment by acoburn** [comment]
If the existing resource `/a/b` is updated, there is a new memento for `/a/b`, but nothing changes for `/a`, neither the last-mod date nor is a new memento created for the parent.

Mementos are created _only_ when updating/creating the target resource. The key thing here is the _target_ resource. So, the act of creating `/a/b` will create a memento only for `/a/b`. It will also update the last-mod value for `/a`, but there will be no new memento created for `/a`.

Furthermore, no mementos are created when deleting a resource. So if `/a/b` is deleted, the only additional operation is that `/a` will have its last-mod value updated (since that resource will no longer have the `</a> ldp:contains </a/b>` triple).

**Comment by ajs6f** [comment]
> So, the act of creating /a/b will create a memento only for /a/b. It will also update the last-mod value for /a, but there will be no new memento created for /a.

I think we've gotten to an important issue. I think this is fine for some folks, but it should not be a Trellis policy. I think Trellis should be responsible for informing the backend of mutations, and then the backend _exclusively_ decides whether they create new Mementos. That is, in fact, what I thought was our policy all along, but I now realize that in your view `MementoService` is how Trellis signals to the backend that a Memento is to be created. 

This is an architectural fault line I'd like to resolve-- which component role owns the decision as to when to create or destroy a Memento? In the view you've presented, it seems to me that Trellis can demand that the backend mint a Memento (via (`MementoService::put`) but cannot delete them or stop the backend from minting others at will. The backend can mint them and delete them at will and must decide how to respond to `MementoService::put` and `::get`. That seems strange at best to me. For example, I might want to mint a new Memento for containers that accepts or loses a new contained resource when it happens, and nothing is stopping me from doing that now, but you clearly don't expect that and you clearly wouldn't consider that correct.

I realize I'm talking about what might eventuate in a serious change to the API, but if we're going to talk about this, better sooner than later.

**Comment by acoburn** [comment]
The view that I'd advocate is that there is a default behavior (or a default expectation of behavior), but that ultimately, an implementation makes its own decisions. I see nothing wrong with an implementation minting and deleting Mementos on its own schedule, but I would like to make sure that there are sufficient hooks in place that a back end has some ideas about when those times might be.

`MementoService::put` is the primary mechanism by which these hints are provided for the creation of mementos, but it is conceivable that there would be others (e.g. by means of `ResourceService::touch`, `::create` or `::replace`). This does introduce some messiness if you're using the behaviors of one service to control the behavior of a separate service, but on the other hand in the T-C* implementation, you are explicitly joining those two services.

If you have ideas about a better way to structure those APIs, I'm all ears.

**Comment by ajs6f** [comment]
Essentially, I'm suggesting stripping `MementoService` down to
```
CompletionStage<Resource> get(IRI identifier, Instant time);
CompletionStage<SortedSet<Instant>> mementos(IRI identifier);
```
I know. I know. That's pretty radical and what's more, I argued as strongly as anyone for the way we do things now. Let's put this larger API issue aside for the next call, cool?

As for this ticket itself, I'm inclined right now to go ahead with a front-end-side `distinct()` approach as originally advocated by @gregjan, which (correct me if I'm wrong @gregjan) didn't seem to incur bad performance penalties, and shouldn't beef on heap except in fairly exceptional cases. We can turn back to it after we have some more discussion about the larger context. 

Does that sound good with everyone? I'll wait to hear from @gregjan before doing anything (which would be making a commit for one form of "distinct" or another and opening a Trellis issue to talk about the larger question).

**Comment by acoburn** [comment]
I'm not against stripping down the `MementoService` -- basically, this is just about removing `MementoService::put`. 

What would you think about using a CDI Event?

```java
@Inject
Event<ResourceModification> modificationEvent;

...

modificationEvent.fire(new ResourceModification(...));
```

and then, if you want to tie into this event stream, you can just have something like this in the `ResourceService` implementation:

```java
public void observeEvent(final @Observes ResourceModification modification) {
   // store the Memento
}
```

Alternatively, the code in the resource service could just handle all of the memento resource creation manually.

Another thought is to introduce a `MementoWriter` interface so that it is easier to plug in various memento backends (e.g. File, Cloud, Database).

**Comment by ajs6f** [comment]
> What would you think about using a CDI Event?

<img src="https://fishnetics.com/wp-content/uploads/2018/05/Mind-Blown.jpg" height="200">

Going home to think about that.

**Comment by ajs6f** [comment]
@gregjan I'm going to close this, since we've moved to the Java-side approach for now.

I am working on a more serious redesign of the Memento action in `t-c*` and I am confident that it will obviate all of these issues, but that's for a separate ticket.

Cool?

**Comment by gregjan** [comment]
Very cool. thanks for the heads up!
