### ISSUE TITLE
Upgrade Cassandra driver

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis-cassandra#62]
Several new versions of the Cassandra driver have been released since we selected 3.6. Upgrade to the current best choice.

**Comment by ajs6f** [comment]
https://docs.datastax.com/en/developer/java-driver/4.0/upgrade_guide/

**Comment by ajs6f** [comment]
This task should include patching driver config through to general Trellis config via:

https://docs.datastax.com/en/developer/java-driver/4.0/manual/core/configuration/#bypassing-typesafe-config

@gregjan this will mean that we can revisit config and devise a general rule for mapping out of ENV. (See [here](https://tamaya.incubator.apache.org/apidocs/development/org/apache/tamaya/spisupport/propertysource/EnvironmentPropertySource.html) at "Application specific…": we could prefix everything in [the driver config properties](https://github.com/datastax/java-driver/blob/4.x/core/src/main/java/com/datastax/oss/driver/api/core/config/DefaultDriverOption.java) with `TRELLIS_` or something like that.)

**Comment by gregjan** [comment]
Yes, either TRELLIS_ or I also feel that starting at CASSANDRA_ would be
unambiguous enough.

**Comment by ajs6f** [comment]
@acoburn Are you interested in selecting a common ENV var prefix for all Trellis-related config?

**Comment by acoburn** [comment]
@ajs6f my opinion is that all core Trellis configuration should start with `TRELLIS_` for ENV vars (or `trellis.` for system properties). For non-core components, I really don't have a strong opinion. For the AWS extension, for example, I use `TRELLIS_S3_` (and `trellis.s3.`) prefix. I have mostly used the `TRELLIS_` prefix to unambiguously differentiate these vars from anything else that may be set in the environment. If it makes sense to use CASSANDRA_ (or something else), that's great, but feel free to use TRELLIS_ if you don't have a more compelling option.

**Comment by gregjan** [comment]
I am fine with the full on TRELLIS_CASSANDRA_FOO env settings. C* itself
(in it's own machines) may use the CASSANDRA_ prefix, which in the mixed
machine docker world could plausibly cause confusion. For instance, often
the env for multiple machines in the same stack is set in a single .env
file.

**Comment by ajs6f** [comment]
Good, then I will roll with `TRELLIS_`, but not using the code to which I pointed above. I realize now that that code is meant for differentiating the config of multiple deployments of the same app in the same machine or container, not our case at all. No problem, I'll just add `TRELLIS_`  "by hand".

**Comment by ajs6f** [comment]
Related to https://github.com/trellis-ldp/trellis/issues/563

**Comment by ajs6f** [comment]
Fixed with https://github.com/trellis-ldp/trellis-cassandra/pull/79/commits/38b4da0704cb1fbfb8107ddfd87f0b7c03ae1e4f
